# Basic
title: Diqing Gou
subtitle: YWNA
welcome_message: Hi, my name is Diqing Gou. I am software developer live in Washington DC area.
description: This theme is ported from Vno Jekyll
creator: <a href="#">@diqingg</a>
cover_color: darkblue
url: '#'

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
  title: Blog
  description: Visit blog

# Navigation buttons in the front page.
nav:
  - { title: Projects, description: My Projects, url: '' }
  # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: 'page/:num/'

# Comment
comment:
  disqus: #
  # duoshuo:

# Social
social:
  github: diqingg
  mail: diqing008@gmail.com

# Google Analytics
ga:
  # id: your_ga_id
  # host: your_host
